/// @file exemdl_calc_rec_error.hpp
/// @brief Reconstruction error calculation module for muon tomography inversion
/// @details Provides functions for computing and analyzing multiple types of reconstruction errors:
///          - Statistical error (from covariance matrix)
///          - Prior error (from prior bounds)
///          - Disabled error (sensitivity to detector removal)
///          - Mixed error (combined error estimate)
///
///          Workflow:
///          1. Output disable-mode visualization results as cross-sections
///          2. Extract error components (statistical, prior bounds, disabled detector impact)
///          3. Compute mixed error combining all error sources
///          4. Write all error fields to cross-section files
///
///          Thread-safety: Not thread-safe. Concurrent calls to write_disable_and_errors may cause race conditions in file I/O.
#pragma once
#include <vector>
#include <Eigen/Dense>

#include "st_NagaInvLooper.hpp"
#include "exemdl_build_detector.hpp"
#include "exemdl_run_inversion.hpp"
#include "cls_Grid3dVoxel.hpp"

/// @brief Reconstruction error calculation module
/// @details Provides functions for computing and analyzing reconstruction errors in the inversion process,
///          including error vector calculation and cross-section output.
namespace exemdl::calc_rec_error {

  /// @brief Check if two sizes are equal and throw if they differ
  /// @param[in] what Description of what is being checked
  /// @param[in] a First size to compare
  /// @param[in] b Second size to compare
  /// @throws std::runtime_error If a != b
  void check_sizes_eq(const char* what, Eigen::Index a, Eigen::Index b);

  /// @brief Write disable-mode visualization and compute/output error vectors
  /// @details Performs combined operations: visualization output of disable test results,
  ///          error vector calculation, and cross-section output.
  ///
  ///          Preconditions:
  ///          - invResAll.center.reconst_res.{vecxf_dens_rec, vecxf_diag_sqrt_cov_dens} must have valid sizes
  ///          - detRes.prior_info_all.{lower,upper}.g3vox must have the same dimensions as reconstruction results
  ///
  /// @param[in] looper Reference to NagaInvLooper instance
  /// @param[in] vec_reconst_res_disabled Reconstruction results when each detector ID is disabled
  /// @param[in] invResAll All inversion results from RunInversion module
  /// @param[in] detRes Build results from BuildDetector module
  /// @param[in] g3vox_merged_input Grid3dVoxel generated by BuildGeometry module (after merge)
  ///
  /// @note g3vox_merged_input is expected to be identical to detRes.prior_info_all.{lower,upper}.g3vox
  /// @param[in] output_prefix Prefix appended to output filenames (e.g., "001").
  ///            Empty string produces default filenames (backward compatible).
  void write_disable_and_errors(
      const NagaInvLooper& looper
    , const std::vector<NagaInv::ReconstResult>& vec_reconst_res_disabled
    , const exemdl::run_inversion::InversionResultsAll& invResAll
    , const exemdl::build_detector::BuildResult& detRes
    , const Grid3dVoxel& g3vox_merged_input
    , const std::string& output_prefix = ""
  );

  /// @brief Overload accepting PriorInfoAll directly (avoids BuildResult copy).
  /// @param[in] output_prefix Prefix appended to output filenames.
  void write_disable_and_errors(
      const NagaInvLooper& looper
    , const std::vector<NagaInv::ReconstResult>& vec_reconst_res_disabled
    , const exemdl::run_inversion::InversionResultsAll& invResAll
    , const exemdl::build_prior::PriorInfoAll& prior_info_all
    , const Grid3dVoxel& g3vox_merged_input
    , const std::string& output_prefix
  );

} // namespace exemdl::calc_rec_error
