/// @file exemdl_build_prior.hpp
/// @brief Prior estimation module for muon tomography inversion.
/// @details Provides functions and data structures for building prior density
///          information (lower/center/upper bounds) used in the inversion stage.
///          Extracted from exemdl_build_detector to separate prior computation
///          from detector array construction.
///
/// @note Coordinate system: z-up, right-handed. All densities in kg/m^3.
/// @note Thread safety: Functions use OpenMP internally (mp_* calls). Not reentrant.
#pragma once

#include <filesystem>
#include <fstream>
#include <string>
#include <vector>
#include <Eigen/Sparse>
#include "cls_DetectorPanelArray.hpp"
#include "cls_Grid3dVoxel.hpp"
#include "cls_Grid2dPillar.hpp"
#include "exemdl_load_parameters.hpp"

/// @namespace exemdl::build_prior
/// @brief Namespace for building prior density information for inversion.
/// @ingroup ExecModule
namespace exemdl::build_prior {

  /// @brief Sparse matrix type alias (float precision).
  using SpMatf = Eigen::SparseMatrix<float>;

  /// @brief Return value of build_arrdet_g3vox_prior.
  struct PriorInfo {
    std::vector<Eigen::VectorXf> vec_vecxf_DL; ///< Density-length vectors from DetectorPanelArray.
    Eigen::VectorXf vecxf_nmuon; ///< Observed muon counts for the prior.
    Grid3dVoxel g3vox; ///< Grid3dVoxel prior generated by copying from g3vox_input.

    /// @brief Save PriorInfo to binary stream.
    void save(std::ofstream& ofs) const;

    /// @brief Load PriorInfo from binary stream.
    void load(std::ifstream& ifs);
  };

  /// @brief Build a single arrdet_g3vox_prior instance.
  /// @param[in] suffix Name suffix (e.g., "_lower", "_center", "_upper").
  /// @param[in] app_params Application parameters.
  /// @param[in] g2pil_shell_upper Pre-built upper Grid2dPillar shell (terrain above g3vox).
  /// @param[in] g2pil_shell_lower Pre-built lower Grid2dPillar shell (terrain below g3vox).
  /// @param[in] g2pil_shell_lateral Pre-built lateral Grid2dPillar shell (terrain surrounding g3vox).
  /// @param[in] has_shell_upper True if upper shell has valid cuboids.
  /// @param[in] has_shell_lower True if lower shell has valid cuboids.
  /// @param[in] has_shell_lateral True if lateral shell has valid cuboids.
  /// @param[in] g3vox_input Merged Grid3dVoxel for reference.
  /// @param[in] voxel_density Uniform density for voxel grid (kg/m^3).
  /// @param[in] shell_density_upper Density for upper shell region (kg/m^3).
  /// @param[in] shell_density_lower Density for lower shell region (kg/m^3).
  /// @param[in] shell_density_lateral Density for lateral shell region (kg/m^3).
  /// @param[in] arrdet_g3vox_input Base DetectorPanelArray for arrdet_g3vox_prior.
  /// @param[in] arrdet_g2pil_naive Source for copying DetectorIndexContainer and bimap.
  /// @return PriorInfo containing density-length vectors, muon counts, and g3vox prior.
  /// @note Uses OpenMP for parallel path/signal computation.
  PriorInfo build_arrdet_g3vox_prior(
      const std::string& suffix
    , const exemdl::load_parameters::AppParameters& app_params
    , const Grid2dPillar& g2pil_shell_upper
    , const Grid2dPillar& g2pil_shell_lower
    , const Grid2dPillar& g2pil_shell_lateral
    , const bool has_shell_upper
    , const bool has_shell_lower
    , const bool has_shell_lateral
    , const Grid3dVoxel& g3vox_input
    , const double voxel_density
    , const double shell_density_upper
    , const double shell_density_lower
    , const double shell_density_lateral
    , const DetectorPanelArray& arrdet_g3vox_input
    , const DetectorPanelArray& arrdet_g2pil_naive
  );

  /// @brief Return value containing lower, center, upper prior information.
  struct PriorInfoAll {
    PriorInfo lower;  ///< Prior information for lower bound density.
    PriorInfo center; ///< Prior information for center density.
    PriorInfo upper;  ///< Prior information for upper bound density.

    /// @brief Save PriorInfoAll to binary stream.
    void save(std::ofstream& ofs) const;

    /// @brief Load PriorInfoAll from binary stream.
    void load(std::ifstream& ifs);
  };

  /// @brief Shell path-length vectors (density-independent, flat layout).
  /// @details Stores PL for each shell region as a single flat VectorXf
  ///          with all panels concatenated. Panel segments are accessed
  ///          via segment(offset, n_ele) using offsets from the DetectorPanelArray.
  ///          PL depends only on geometry, not density.
  ///          vecxf_non_rec_vox_PL holds the per-element PL contribution from
  ///          mountain-interior voxels that fail the n_hit_det filter
  ///          (i.e. voxels not present in vec_spmat_PL columns). Required
  ///          to reconstruct the same prior PL/DL as the legacy ray-tracing
  ///          path build_arrdet_g3vox_prior.
  struct ShellPL {
    Eigen::VectorXf vecxf_upper_PL;          ///< PL through upper shell (flat, all panels).
    Eigen::VectorXf vecxf_lower_PL;          ///< PL through lower shell (flat, all panels).
    Eigen::VectorXf vecxf_lateral_PL;        ///< PL through lateral shell (flat, all panels).
    Eigen::VectorXf vecxf_non_rec_vox_PL;  ///< PL through mountain voxels filtered out by n_hit_det.

    /// @brief Save ShellPL to a directory (4 binary files).
    /// @param[in] dir Directory to save files into.
    void save(const std::filesystem::path& dir) const;

    /// @brief Load ShellPL from a directory.
    /// @param[in] dir Directory containing the binary files.
    /// @note vecxf_non_rec_vox_PL is loaded only if the file exists, for backward
    ///       compatibility with checkpoints written before this field was added.
    static ShellPL load(const std::filesystem::path& dir);
  };

  /// @brief Compute shell path lengths (density-independent, once per geometry).
  /// @param[in] app_params Application parameters.
  /// @param[in] arrdet_g3vox_input Base detector array (for element geometry).
  /// @param[in] g2pil_shell_upper Upper shell grid.
  /// @param[in] g2pil_shell_lower Lower shell grid.
  /// @param[in] g2pil_shell_lateral Lateral shell grid.
  /// @param[in] has_shell_upper True if upper shell is valid.
  /// @param[in] has_shell_lower True if lower shell is valid.
  /// @param[in] has_shell_lateral True if lateral shell is valid.
  /// @return ShellPL containing per-panel PL vectors for each shell.
  /// @note Uses OpenMP via pathcalc::g2pil::mp_calc_PL.
  ShellPL build_shell_PL(
      const exemdl::load_parameters::AppParameters& app_params
    , const DetectorPanelArray& arrdet_g3vox_input
    , const Grid2dPillar& g2pil_shell_upper
    , const Grid2dPillar& g2pil_shell_lower
    , const Grid2dPillar& g2pil_shell_lateral
    , bool has_shell_upper
    , bool has_shell_lower
    , bool has_shell_lateral
  );

  /// @brief Rebuild prior from saved PL data (cheap, no ray tracing).
  /// @details Reconstructs DL from shell PL vectors + vec_spmat_PL (g3vox T) + density_quad,
  ///          then runs signal computation and grouping.
  /// @param[in] suffix Name suffix (e.g., "_lower", "_center", "_upper").
  /// @param[in] app_params Application parameters.
  /// @param[in] shell_pl Pre-computed shell path lengths.
  /// @param[in] vec_spmat_PL Sparse path-length matrices for g3vox (T component).
  /// @param[in] g3vox_input Merged Grid3dVoxel for reference.
  /// @param[in] voxel_density Uniform density for voxel grid (kg/m^3).
  /// @param[in] shell_density_upper Density for upper shell (kg/m^3).
  /// @param[in] shell_density_lower Density for lower shell (kg/m^3).
  /// @param[in] shell_density_lateral Density for lateral shell (kg/m^3).
  /// @param[in] arrdet_g3vox_input Base DetectorPanelArray.
  /// @param[in] arrdet_g2pil_naive Source for bimap copy.
  /// @return PriorInfo containing density-length vectors, muon counts, and g3vox prior.
  /// @note Uses OpenMP for signal computation.
  /// @note When DetectorPanel::ParameterLists::tf_save_arrdet_prior is true, writes the
  ///       prior DetectorPanelArray to det/arrdet_g3vox_prior(suffix).bin under the current
  ///       output directory. PriorInfo drops the array itself, and plot_det_arrdet.py reads
  ///       DetectorPanelArray binaries only. Default false: about 160 MB per file.
  PriorInfo rebuild_prior_from_shell_PL(
      const std::string& suffix
    , const exemdl::load_parameters::AppParameters& app_params
    , const ShellPL& shell_pl
    , const std::vector<SpMatf>& vec_spmat_PL
    , const Grid3dVoxel& g3vox_input
    , double voxel_density
    , double shell_density_upper
    , double shell_density_lower
    , double shell_density_lateral
    , const DetectorPanelArray& arrdet_g3vox_input
    , const DetectorPanelArray& arrdet_g2pil_naive
  );

  /// @brief Build all prior pairs (lower, center, upper).
  /// @param[in] app_params Application parameters.
  /// @param[in] g2pil_shell_upper Pre-built upper Grid2dPillar shell (terrain above g3vox).
  /// @param[in] g2pil_shell_lower Pre-built lower Grid2dPillar shell (terrain below g3vox).
  /// @param[in] g2pil_shell_lateral Pre-built lateral Grid2dPillar shell (terrain surrounding g3vox).
  /// @param[in] has_shell_upper True if upper shell has valid cuboids.
  /// @param[in] has_shell_lower True if lower shell has valid cuboids.
  /// @param[in] has_shell_lateral True if lateral shell has valid cuboids.
  /// @param[in] g3vox_input Merged Grid3dVoxel.
  /// @param[in] avr_dens_lower_center_upper Array of [lower, center, upper] voxel densities (kg/m^3).
  /// @param[in] shell_density_upper Density for upper shell region (kg/m^3).
  /// @param[in] shell_density_lower Density for lower shell region (kg/m^3).
  /// @param[in] shell_density_lateral Density for lateral shell region (kg/m^3).
  /// @param[in] arrdet_g3vox_input Base DetectorPanelArray for prior construction.
  /// @param[in] arrdet_g2pil_naive Source for copying DetectorIndexContainer.
  /// @return PriorInfoAll containing lower, center, upper prior information.
  /// @details Calls build_arrdet_g3vox_prior 3 times with lower, center, upper suffixes.
  PriorInfoAll build_prior_info_all(
      const exemdl::load_parameters::AppParameters& app_params
    , const Grid2dPillar& g2pil_shell_upper
    , const Grid2dPillar& g2pil_shell_lower
    , const Grid2dPillar& g2pil_shell_lateral
    , const bool has_shell_upper
    , const bool has_shell_lower
    , const bool has_shell_lateral
    , const Grid3dVoxel& g3vox_input
    , const std::array<double,3>& avr_dens_lower_center_upper
    , const double shell_density_upper
    , const double shell_density_lower
    , const double shell_density_lateral
    , const DetectorPanelArray& arrdet_g3vox_input
    , const DetectorPanelArray& arrdet_g2pil_naive
  );

} // namespace exemdl::build_prior
